title: Atikul Gazi
description: Atikul Gazi's online CV built with Jekyll and the cvless theme.
baseurl: ""
url: https://atiksplanet.github.io/

#theme: cvless

# site settings
taglong: iOS Developer #Atik's online CV
tagshort: resume #Jekyll theme

# author settings
author:
  name: Atikul Gazi
  email: atiksplanet@gmail.com
photo: assets/files/IMG_0307.jpeg
joblines:
  - Samsung Electronics, Technical Lead Engineer
  - SmartThings Development Group (SDG), IoT Platform Team
  - Bir Uttam CR Dutta Rd, Dhaka 1205, Bangladesh
address: Dhaka, Bangladesh
phone: +880 1914 088481

# profile links
profile:
  facebook: https://www.facebook.com/atiksplanet/
  x: https://x.com/atiksplanet
  mastodon: https://mastodon.social/@atiksplanet
  bluesky: https://bsky.app/profile/atiksplanet.bsky.social
  instagram: https://www.instagram.com/atiksplanet
  linkedin: https://www.linkedin.com/in/atiksplanet
  xing: https://www.xing.com/profile/atiksplanet
  stackoverflow: https://stackoverflow.com/users/0000000/atiksplanet
  medium: https://medium.com/@atiksplanet
  github: https://github.com/atiksplanet
  cv: true

# build settings
permalink: pretty
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  sourcemap: never
  
